server:
  port: 20003
  servlet:
    context-path: /

upload:
  rootPath: D:\uploads
  domain: http://img.xm-bt.com/

# 配置文件加密key
jasypt:
  encryptor:
    password: skeleton

spring:
  application:
    name: admin-server
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xm_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  # Redis
  redis:
    host: 127.0.0.1
    #password: 123456
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000s
    #password: 69F0ef5dd1d62ab48b13834286403A

  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 500000000
      max-request-size: 500000000

skeleton:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10

# 忽略鉴权url
ignored:
  urls:
    - /skeleton/permission/getMenuList/**
    - /skeleton/common/**
    - /
    - /img/**
    - /css/**
    - /js/**
    - /fonts/**
    - /static/**
    - /skeleton/ueditor/**
    - /ueditor/**
    - /*.*

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/**/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xm.admin.*.*.entity
  typeEnumsPackage: com.xm.admin.*.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志
logging:
  file: D:/logs/com.xm.admin.log
